### ISSUE TITLE
Add "ordering" field to "extras" pane for .do .po .dsk disk images

### ISSUE THREAD

**Issue by hippietrail** [dmolony/DiskBrowser2#2]
I think there's nothing telling us the order of the sectors in DOS 3 and ProDOS raw disk image files, the ones that have `.dsk`, `.do`, and `.po` file extensions.

Perhaps I'm missing it but if not it would be nice to add this info to the "extras" panel for those file types.

My use case is I've been implementing these disk image types in my own little project and tools such as yours are very handy for checking against to see if I'm getting things right.

Nice little tool, after going down a rabbit hole to install JavaFX on Mac (-:

**Comment by dmolony** [comment]
The interleave value on the meta tab has that information. See BlockReader.java (in FileSystem) for details.
